INSERT INTO "ADMIN"("ADMIN_ID", "DID", "NAME", "PASSWORD") VALUES ('A101', '1', 'Riad', 'a1a1a1');
INSERT INTO "ADMIN"("ADMIN_ID", "DID", "NAME", "PASSWORD") VALUES ('A201', '2', 'Shojol', 'a2a2a2');
INSERT INTO "ADMIN"("ADMIN_ID", "DID", "NAME", "PASSWORD") VALUES ('A301', '3', 'Tanim', 'a3a3a3');
INSERT INTO "ADMIN"("ADMIN_ID", "DID", "NAME", "PASSWORD") VALUES ('A401', '4', 'Imdadul', 'a4a4a4');
INSERT INTO "ADMIN"("ADMIN_ID", "DID", "NAME", "PASSWORD") VALUES ('A501', '5', 'Masud', 'a5a5a5');
