INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('101', '101', '1', '	Structured Programming Language                  ', '3.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('102', '102', '1', '	Structured Programming Language Sessional        ', '4');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('103', '104', '1', 'Data Structures and Algorithms                    ', '3');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('104', '103', '1', 'Data Structures and Algorithms Sessional          ', '2.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('105', '103', '1', 'Software Engineering                              ', '1.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('106', '102', '1', 'Software Engineering Sessional                    ', '3.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('107', '104', '1', 'Computer Security                                 ', '3.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('108', '101', '1', 'Computer Security Sessional                       ', '3');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('201', '204', '2', 'Electrical Circuits                               ', '3.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('202', '202', '2', 'Electrical Circuits Laboratory                    ', '4');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('203', '201', '2', 'Electronic Circuits                               ', '3');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('204', '204', '2', 'Electronic Circuits Laboratory                    ', '2.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('205', '201', '2', 'Power System                                      ', '1.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('206', '203', '2', 'Power System Laboratory                           ', '3.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('207', '203', '2', 'Microprocessors and Embedded Systems              ', '3.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('208', '202', '2', 'Microprocessors and Embedded Systems Laboratory   ', '3');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('301', '302', '3', 'Introduction to Mechanical Engineering            ', '3.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('302', '303', '3', 'Mechanical Engineering Drawing                    ', '4');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('303', '302', '3', 'Engineering Thermodynamics                        ', '3');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('304', '304', '3', 'Engineering Thermodynamics Sessional              ', '2.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('305', '301', '3', 'Fluid Mechanics                                   ', '1.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('306', '301', '3', 'Fluid Mechanics Sessional                         ', '3.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('307', '304', '3', 'Internal Combustion Engines                       ', '3.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('308', '303', '3', 'Power Plant Engineering Sessional                 ', '3');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('401', '403', '4', 'Civil Engineering Drawing                         ', '3.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('402', '403', '4', 'Surveying                                         ', '4');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('403', '401', '4', 'Details of Constructions                          ', '3');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('404', '404', '4', 'Materials Sessional                               ', '2.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('405', '402', '4', 'Design of Steel Structures                        ', '1.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('406', '404', '4', 'Steel Structures Design Sessional                 ', '3.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('407', '402', '4', 'Analysis of Indeterminate Structures              ', '3.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('408', '401', '4', 'Building Design Sessional                         ', '3');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('501', '504', '5', 'Introduction to Metallurgy and Materials          ', '3.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('502', '501', '5', 'Phase Diagrams and Transformation                 ', '4');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('503', '503', '5', 'Crystallography and Structure of Materials        ', '3');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('504', '502', '5', 'Crystallography and Structure Sessional           ', '2.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('505', '501', '5', 'Physical Properties of Materials                  ', '1.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('506', '502', '5', 'Application of CAD to Materials Processing        ', '3.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('507', '503', '5', 'Physical Metallurgy of Steels and Heat Treatment  ', '3.5');
INSERT INTO "COURSE"("CID", "TID", "DID", "NAME", "CREDIT_HR") VALUES ('508', '504', '5', 'Heat Treatment and Microstructure Sessional       ', '3');
